== Create a custom component
'''
Tyro provides components for most common html tags but it also allows to create custom components.

=== Creation of the component
TODO

=== Use of the component

The created components can be used as Tyro core component and Tyro web Component, as shown in the following example

==== Example of use of custom component DisplayedValue

to match with the 6th span with class "cell-inner" :

[source, groovy]
static DisplayedValue getName_Clicable_Header() {
    $('span.cell-inner:eq(5)') as DisplayedValue
}

=== Examples of custom components

==== Span with title and text

[source, groovy]
class DisplayedValue extends Span implements TextSupport, TitleSupport {
    String text() {
        return config.evaluator.eval(id(), "it.text()").replaceAll("[\n\t]", "").trim()
    }
    @Override
        String title() {
            return config.evaluator.eval(id(), "it.attr('title')")
    }
}

==== Popup of css type "div.ui-dialog" with 2 buttons

[source, groovy]
@CssIdentifier("div.ui-dialog")
class Dialog extends Div implements TextSupport {
    String text() {
        Div content = find(By.css('div.ui-dialog-content:first')).get(0) as Div
        return config.evaluator.eval(content.id(), "it.text()")
    }
    Button getBt_OK() {
        find(By.css('button:eq(0)')).get(0) as org.testatoo.bundle.html5.Button
    }
    Button getBt_cancel() {
        find(By.css('button:eq(1)')).get(0) as org.testatoo.bundle.html5.Button
    }
}

==== Popups of css type "div" with title and text

- first example

[source, groovy]
class Popup extends Div implements TextSupport {
    String title() {
        return config.evaluator.eval(id(), "it.find('h2').text()").replaceAll("[\n\t]", "").trim()
    }
    String text() {
        return config.evaluator.eval(id(), "it.find('p').text()").replaceAll("[\n\t]", "").trim()
    }
}

- second example

[source, groovy]
class Modale extends Div implements TextSupport {
    String title() {
        return config.evaluator.eval(id(), "it.find('h2.modal-title').text()").replaceAll("[\n\t]", "").trim()
    }
    String text() {
        return config.evaluator.eval(id(), "it.find('h2.modal-body').text()").replaceAll("[\n\t]", "").trim()
    }
}

==== Page of css type "div" with h2 title

[source, groovy]
class SubPage extends Div {
    String title() {
        return config.evaluator.eval(id(), "it.find('h2:first').text()"). replaceAll("[\n\t]", "").trim()
    }
}

==== Table cell with a checkbox

[source, groovy]
class CellCheckBox extends Td {
    CheckBox getCheckBox() {
        return find(By.css('input[type=checkbox]'), InputTypeCheckBox)[0]
    }
}

==== Div with text

[source, groovy]
class Message extends Div implements TextSupport {
    String text() {
        return config.evaluator.eval(id(), "it.text()"). replaceAll("[\n\t]", "").trim()
    }
}

==== P with text

[source, groovy]
class ParagraphMessage extends P implements TextSupport {
    String text() {
        return config.evaluator.eval(id(), "it.text()"). replaceAll("[\n\t]", "").trim()
    }
}

==== Tooltip defined as a title

[source, groovy]
@CssIdentifier('label')
class ToolTip extends Component implements TitleSupport {
    @Override String title() {
        return config.evaluator.eval(id(), "it.attr('title')"). replaceAll("[\n\t]", "").trim()
    }
}

==== Textarea with an angular tag that overrides the html valid property

[source, groovy]
class CustTextArea extends TextArea implements ValiditySupport {
    @Override boolean valid() {
        !config.evaluator.check(id(), "it.hasClass('ng-invalid')")
    }
}