=== Component selection
'''

The fonctional objets used in the tests are instances of Tyro or specific Components.
Here are the different ways of building these objects dependently of html tag and attribute.

==== The $ function

The $ function is the access point for fetching component on the page. The $ function accepts a CSS3 selector to target your component.
The signature of the $ function is showed in the following examples.

[cols="1,1,3a", options="header"]
|===
|Attribute |attribute value |Match with DOM element

|id
|clientLastName
|TextField last_name = $('*[blue]#[id="clientLastName"]#*') as InputTypeText

| >|_(shortcut)_
|TextField last_name = $('*[blue]##clientLastName#*') as InputTypeText

[IMPORTANT]
====
the shortcut *# cannot be used for ids with '.' inside* (_not supported by JQuery_)
====

|class
|txt-secondary
|TextField last_name = $('*[blue]#[class="txt-secondary"]#*') as InputTypeText

2+>|_(shortcut)_
|TextField last_name = $('*[blue]#.txt-secondary#*') as InputTypeText


|name
|owner-last-name
|TextField last_name = $('*[blue]#[name="owner-last-name"]#*') as InputTypeText

|data-role
|myRole
|TextField last_name = $('*[blue]#[data-role = "myRole"]#*') as InputTypeText

|===

===== Other examples

*the second input with type = 'text'*
[subs="quotes"]
----
    TextField last_name = $('*input:eq(1)*') as InputTypeText
----
*the first h3 element in the page*
[subs="quotes"]
----
    Heading sectionSubTitle = $('*h3:eq(0)*') as H3
----
*the third button in the page with 'chButSubmit' name*
[subs="quotes"]
----
     Button go_button =  $('*[name="chButSubmit"]:eq(2)*') as org.testatoo.bundle.html5.Button
----
*the first table in the form with 'operationForm' name*
[subs="quotes"]
----
      DataGrid getOperationTable = $('*[name="OperationImmediateForm"]* > table:eq(0)') as Table
----

[IMPORTANT]
====
Once the component is selected, it *MUST BE TYPED* through the *"as"* keyword.
====
Our experience demonstrated that *we never need complex selector.* If you write tests first, we use the semantic
carried by the tested component. In the code, this is reflected by a custom tag, the sequence in the page, a role
attribute, or an id. In all these cases, a css3 selector is more than enough.

// TODO : examples (custom tag : with Angular Directive or Web Components)

TODO : PARTIE A REVISER

In Tyro you never select an anonymous DOM element. Every DOM element must be the representation of a UI concept.
But wait a moment: How can you know if a button is a button!? Indeed, in HTML, a Button can be represented in many ways:

[source, html]
-------------------------------------------------------------------------------
<button id="button">My Button</button>
<input id="button" type="button" value="My Button">
<input id="button" type="submit" value="My Button">
-------------------------------------------------------------------------------

This is the magic of Tyro. We will see later how it works and how to override this behavior and easily add new component types.

[IMPORTANT]
====
The $ function *NEEDS* to target a *UNIQUE* component. If you want to work with a list of components you need to use the $$ function.
====

==== The $$ function

The following code fails because through the selector expression, we try to target a list of items (options) of a select to evaluate their visibility.
[source, groovy]
-------------------------------------------------------------------------------
Item item = $('select option') as Item
assert item.visible()
-------------------------------------------------------------------------------

TODO

==== The find function
TODO
The find function is used when building specific components

