== Quick Start

We give you 2 ways to quickly start your Tyro project : TODO

- an empty template to start from scratch
- a test application built from this template to see examples and best practices

We also give you the Tyro application with added Cucumber scenarios

=== Installation with Maven
'''

These are the dependencies to include if you want to integrate Tyro in your Maven installation file.
The following installation if for JUnit. For another test runner, adapt the first dependency.

[source, xml, subs="normal"]
-------------------------------------------------------------------------------
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.12</version>
    <scope>test</scope>
</dependency>
<dependency>
   <groupId>sc.tyro</groupId>
   <artifactId>tyro</artifactId>
   <version>{tyro-version}</version>
   <scope>test</scope>
</dependency>
-------------------------------------------------------------------------------


ou : (complet avec explications ? TODO) :

<1> tyro core (Objets du Domaine + Langage)
<2> Le module Html5 de tyro
<3> Un plugin pour récupérer les binaires webdriver

=== A first UI test example with JUnit
'''

[source,groovy,linenums]
[subs="verbatim,attributes"]
----
//include::{basepath}/test/groovy/doc/junit/JunitStarterTest.groovy[]
----

<1> The browser is launched through a Webdriver Wraper (WebDriverEvaluator).

<2> Visit the page to be tested: Tyro is ready.

<3> Write you first test ($ usage is explained after)

<4> At the end of the test don't forget to close the browser.