== Introduction

'''

Tyro is a web user interface testing tool. It's the result of numerous real-world observations of developers in the trenches in the area of GUI testing.
Working for many years to promote the *TDD/BDD* approaches, we often faced difficulties in their implementation for the graphical layer of applications.

The *"TEST FIRST"* principle excludes all scenario recorder based approaches that only allow you to write "at posteriori" tests.
Our experience has taught us that this path is a dead-end.

Another problem is UI tests are brittle and costly! We do think that this is due to the lack of abstraction in existing UI testing tools.

Tyro provides, on one hand, an abstraction of the UI business domain through an expressive API and, on the other hand, a way to express this domain via a DSL (a button semantically stays a button, whatever the technology).
With Tyro, you can therefore write tests with a seldom achieved level of expressiveness and make those tests INDEPENDENT of the underlying technology.

Therefore Tyro can transform tests in real assets, present throughout the life of the application and always in tune with the latest version of the application.

Tyro is an opinionated tool. It forces the user to see and use the domain layer as a composition and aggregation of UI components (in Tyro, everything is a UI component).

Tyro is a library to write functional tests. Functional tests means **SPECIFICATIONS**.

'''

As a **SPECIFIER**, I want to express my test (intention) *BEFORE* UI is coded. So, if the intention is to have
a page with two radio buttons to select the gender (male or female), the test can be expressed like this :

TODO
//----
//include::{spec}/gender.spec[]
//----

The Tyro syntax to express this specification is:

TODO

//[source,groovy,indent=0]
//[subs="verbatim,attributes"]
//----
//include::{code}/SpecTest.groovy[tag=gender-spec]
//----

So we can see that *Tyro is close to the natural language.*

TODO : Cucumber scenarios on Tyro

