== Writing tests

=== Writing a Tyro test
.First test
[source, groovy]
@Test
void task_form_should_have_expected_properties_and_behaviours() {
    textField("What's need to be done ?").should {
        be focused
        have length(30)
        be empty
    }
    button('Add').should { be disabled }
    fill textField("What's need to be done ?") with 'Call the doctor'
    button('Add').should { be enabled }
}

=== Writing a Cucumber scenario

.Feature: Add a todo in a todo list

  Scenario: Add a todo
    Given Anna has already 3 todos in her todo list
      | done | todo                 |
      | no   | Write a poem         |
      | no   | Fix your broken iPad |
      | yes  | Read the latest news |

    When Anna adds 'Call the doctor' as a new todo

    Then Anna should have 4 todos in her todo list
      | done | todo                 |
      | no   | Write a poem         |
      | no   | Fix your broken iPad |
      | yes  | Read the latest news |
      | no   | Call the doctor      |

==== Writing steps used in the scenario

[source, groovy]
Given(~/^(.*) has already (\d+) todos in her todo list$/) {String user, int number, DataTable data ->
    waitUntil { todo_list().items().size() == number }
    checkTable(data)
}
[source, groovy]
When(~/^(.*) adds '(.*)' as a new todo/) { String user, String todo ->
    fill textField("What's need to be done ?") with todo
    clickOn button('Add')
}
[source, groovy]
Then(~/^(.*) should have (\d+) todos in her todo list$/) { String user, int number, DataTable data ->
    waitUntil { todo_list().items().size() == number }
    checkTable(data)
}

==== Selection of the the components used in the steps

class ComponentFactory {
...
static ListView todo_list() { $('ul:first') as TodoList }
...
}
