name: Chrome Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests Under Chrome
    runs-on: ubuntu-20.04
    env:
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'liberica'
      - run: ./mvnw clean package
      - run: .github/actions/code-coverage.sh