name: Chrome Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Run Tests Under Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'liberica'
      - run: ./mvnw clean package

  quality:
    name: Run Quality Gates
    needs: [ tests ]
    runs-on: ubuntu-latest
    env:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'liberica'
      - uses: JetBrains/qodana-action@main
        with:
          args: |
            --source-directory,core,
          artifact-name: qodana-core
      - uses: JetBrains/qodana-action@main
        with:
          args: |
            --source-directory,web,
          artifact-name: qodana-web

  coverage:
    name: Run Code Coverage
    needs: [ tests ]
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'liberica'
      - run: ./mvnw clean package
      - run: .github/actions/code-coverage.sh