name: Publish documentation
on:
  push:
    branches: [ master ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: Build core
        run: ./mvnw clean package -f core/pom.xml -DskipTests
      - name: Build web
        run: ./mvnw clean package -f web/pom.xml -DskipTests
      - name: Build documentation
        run: ./mvnw clean package  -f documentation/pom.xml
      - name: Publish Documentation
        run: .github/actions/documentation.sh
