name: Publish documentation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Tyro
        run: ./mvnw clean install -DskipTests
      - name: Publish Documentation
        run: .github/actions/documentation.sh
