name: Firefox Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests Under Firefox
    runs-on: ubuntu-latest
    env:
      browser: firefox
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: 11
      - run: ./mvnw clean package
