name: Chrome Web Bundle Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: Build and Tests for Firefox
        run: ./mvnw clean package -Dbrowser=firefox
      - name: Send code coveragte to CodeClimate
        run: .github/actions/codeclimate.sh